#base
hspace
    = ' ' | '\t'
    ;

line
    = '\n' | '\r' | '\f'
    ;

lines
    = {line}+
    ;

identifier
    = identifier_with_subscript
    | identifier_alone
    ;

identifier_with_subscript::IdentifierSubscript
    = left:identifier_alone '_' right+:identifier_alone {right+:identifier_alone}
    ;


identifier_alone::IdentifierAlone
    = !KEYWORDS value:/[A-Za-z]/ | '`' id:/[^`]*/ '`'
    #= !KEYWORDS value:/[A-Za-z]/ | '`' id:/[\p{L}\p{M}A-Za-z0-9\s\u2190-\u21FF\u1000-\uFFFFF]*/ '`'
    ;


description
    = !KEYWORDS /[A-Za-z0-9][A-Za-z0-9\t ]*/
    ;

desc_identifier
    = !KEYWORDS '`' /[A-Za-z][[A-Za-z0-9]*/ '`'
    ;

separator
    =
    | line
    | ';'
    ;

separator_with_space
    = {hspace} separator {hspace}
    ;

blank
    = {(hspace | separator)}
    ;

params_separator
    = ','|';'|'x'|'×'
    ;