#base
hspace
    = ' ' | '\t'
    ;

line
    = '\n' | '\r' | '\f'
    ;

lines
    = {line}+
    ;

identifier
    = identifier_with_subscript
    | identifier_alone
    ;

identifier_with_subscript::IdentifierSubscript
    = left:identifier '_' right+:identifier {right+:identifier}
    ;


identifier_alone::IdentifierAlone
    = !KEYWORDS value:/[A-Za-z]/
    ;


description
    = !KEYWORDS /[A-Za-z0-9][A-Za-z0-9\t ]*/
    ;

desc_identifier
    = !KEYWORDS '`' /[A-Za-z][[A-Za-z0-9]*/ '`'
    ;

separator
    =
    | line
    | ';'
    ;

separator_with_space
    = {hspace} separator {hspace}
    ;

blank
    = {(hspace | separator)}
    ;