KEYWORDS
    = TRACE
    | VEC
    | DIAG
    | ID
    | EIG
    | CONJ
    | RE
    | IM
    | INV
    | DET
    | SVD
    | RANK
    | NULL
    | ORTH
    | QR
    | DERIVATIVE
    | VDOTS
    | CDOTS
    | IDDOTS
    | DDOTS
    | WHERE
    | SUM
    | IF
    | OTHERWISE
    | IS
    | IN
    | SIN
    | COS
    | ASIN
    | ARCSIN
    | ACOS
    | ARCCOS
    | TAN
    | ATAN
    | ARCTAN
    | ATAN2
    | EXP
    | LOG
    | LN
    | SQRT
    ;

TRACE = 'trace';
VEC = 'vec';
DIAG = 'diag';
ID = 'Id';
EIG = 'eig';
CONJ = 'conj';
RE = 'Re';
IM = 'Im';
INV = 'inv';
DET = 'det';
SVD = 'svd';
RANK = 'rank';
NULL = 'null';
ORTH = 'orth';
QR = 'qr';
DERIVATIVE = '\u2202';
VDOTS = '\u22EE';   #⋮
CDOTS = '\u22EF';   #⋯
IDDOTS = '\u22F0';  #⋰
DDOTS = '\u22F1';   #⋱
WHERE = 'where';
SUM = 'sum' | '∑';
SYMMETRIC = 'symmetric';
DIAGONAL = 'diagonal';
IF = 'if';
OTHERWISE = 'otherwise';
IS = 'is';
IN = 'in';
SIN = 'sin';
ASIN = 'asin';
ARCSIN = 'arcsin';
COS = 'cos';
ACOS = 'acos';
ARCCOS = 'arccos';
TAN = 'tan';
ATAN = 'atan';
ARCTAN = 'arctan';
ATAN2 = 'atan2';
EXP = 'exp';
LOG = 'log';
LN = 'ln';
SQRT = 'sqrt';