KEYWORDS
    = TRACE
    | VEC
    | DIAG
    | ID
    | EIG
    | CONJ
    | RE
    | IM
    | INV
    | SQRT
    | EXP
    | LOG
    | DET
    | SVD
    | RANK
    | NULL
    | ORTH
    | QR
    | DERIVATIVE
    | VDOTS
    | CDOTS
    | IDDOTS
    | DDOTS
    | WHERE
    | SUM
    | IF
    | OTHERWISE
    | IS
    | 'I'
    ;

TRACE = 'trace';
VEC = 'vec';
DIAG = 'diag';
ID = 'Id';
EIG = 'eig';
CONJ = 'conj';
RE = 'Re';
IM = 'Im';
INV = 'inv';
SQRT = 'sqrt';
EXP = 'exp';
LOG = 'log';
DET = 'det';
SVD = 'svd';
RANK = 'rank';
NULL = 'null';
ORTH = 'orth';
QR = 'qr';
DERIVATIVE = '\u2202';
VDOTS = '\u22EE';   #⋮
CDOTS = '\u22EF';   #⋯
IDDOTS = '\u22F0';  #⋰
DDOTS = '\u22F1';   #⋱
WHERE = 'where';
SUM = 'sum' | '∑';
SYMMETRIC = 'symmetric';
DIAGONAL = 'diagonal';
IF = 'if';
OTHERWISE = 'otherwise';
IS = 'is';