@@grammar::LA
@@whitespace :: /(?!.*)/     #parse whitespace manually
@@left_recursion::True

start
    =
    statements $
    ;

#include :: "linear_algebra/la_grammar/keywords.ebnf"
#include :: "linear_algebra/la_grammar/number.ebnf"
#include :: "linear_algebra/la_grammar/operators.ebnf"
#include :: "linear_algebra/la_grammar/matrix.ebnf"
#include :: "linear_algebra/la_grammar/base.ebnf"



statements::Statements
    =
    | value+:statements {hspaces} {separator}+ {hspaces} value+:statement {hspaces}
    | value+:statements {hspaces} {separator}+ {hspaces}
    | value+:statement {hspaces}
    ;

statement
    =
    | assignment
    | expression
    ;

expression
    =
    | addition
    | subtraction
    | term
    #| operations
    | {}
    ;

assignment::Assignment
    =
    left:identifier {hspace} '=' {hspace} right:expression {hspace}
    ;

term
    =
    | multiplication
    | division
    | operations
    | factor
    ;

factor
    =
    | subexpression
    | identifier
    | number
    | matrix
    ;

subexpression::Subexpression
    =
    '(' {hspaces} value:expression {hspaces} ')'
    ;