#matrix
matrix::Matrix
    = '[' {hspace} value:rows {hspace} ']'
    ;

rows::MatrixRows
    =
    | value+:rows {separator_with_space}+ value+:row {hspace}
    | value+:rows {separator_with_space}+
    | value+:row {hspace}
    ;

row::MatrixRow
    =
    | value+:row_with_commas {hspace} value+:expr_in_matrix
    | value+:row_with_commas
    | value+:expr_in_matrix
    ;

row_with_commas::MatrixRowCommas
    #= ( left+:row_with_commas | left+:expr_in_matrix ) {hspace} ',' {hspace} value+:expr_in_matrix
    =
    | value+:row_with_commas {hspace} value+:expr_in_matrix ({hspace} ',' | {hspace}+)
    | {hspace} value+:expr_in_matrix ({hspace} ',' | {hspace}+)
    ;

expr_in_matrix::SingleValueModel
    =
    | value:addition_in_matrix
    | value:subtraction_in_matrix
    | value:term_in_matrix
    | value:(vdots | cdots | iddots | ddots)
    #| {}
    ;

addition_in_matrix::Add
    =
    left:term_in_matrix op:'+' right:expr_in_matrix
    ;


subtraction_in_matrix::Subtract
    =
    left:term_in_matrix op:'-' right:expr_in_matrix
    ;


term_in_matrix
    =
    | multiplication_in_matrix
    | division_in_matrix
    | factor
    ;

multiplication_in_matrix
    =
    factor '*' term_in_matrix
    ;

division_in_matrix
    =
    factor '/' term_in_matrix
    ;

vdots::MatrixVdots
    = VDOTS
    ;

cdots::MatrixCdots
    = CDOTS
    ;

iddots::MatrixIddots
    = IDDOTS
    ;

ddots::MatrixDdots
    = DDOTS
    ;