#operators
operations
    =
    | trace_operation
    | eig_operation
    | derivative_operation
    | inner_product
    | matrix_operator
    | power_operation
    ;

addition::Add
    =
    left:term {hspaces} op:'+' {hspaces} right:expression
    ;


subtraction::Subtract
    =
    left:term {hspaces} op:'-' {hspaces} right:expression
    ;


multiplication::Multiply
    =
    left:term op:'*' right:term
    | left:term {hspaces} right:term
    ;


division::Divide
    =
    #left:term {hspaces} op:'/' {hspaces} right:term
    left:factor {hspaces} op:'/' {hspaces} right:term
    ;


dot_multiplication
    = identifier '.*' identifier
    ;

trace_operation
    = TRACE '(' {hspaces} identifier {hspaces} ')'
    ;

eig_operation
    = EIG '(' {hspaces} identifier {hspaces} ')'
    ;


derivative_operation::Derivative
    = DERIVATIVE value:identifier;

power_operation
    = identifier {hspaces} '^' {hspaces} identifier
    ;

inner_product::InnerProduct
    = '<' {hspaces} left:identifier {hspaces} ',' {hspaces}  right:identifier {hspaces} '>';

matrix_operator
    = identifier '_' identifier
    | identifier '_' desc_identifier;
