@@grammar::LA
@@whitespace :: /(?!.*)/     #parse whitespace manually
@@left_recursion::True
# Only parse directives and where block

start::Start
    = {{separator_with_space} directive+:Directive {{separator_with_space}+ directive+:Directive}} ((blank:/[\s\S]*(?=where)/ {'where' {separator_with_space}+ cond:where_conditions} {blank})|(blank:/[\s\S]*/))
    ;

#include :: "linear_algebra/la_grammar/keywords.ebnf"
#include :: "linear_algebra/la_grammar/base.ebnf"
#include :: "linear_algebra/la_grammar/shared.ebnf"



