@@grammar::LA
@@whitespace :: /(?!.*)/     #parse whitespace manually
@@left_recursion::True
# Only parse directives and where block

start::Start
    = {{separator_with_space} directive+:Directive {{separator_with_space}+ directive+:Directive}} ((blank:/[\s\S]*(?=where)/ {'where' {separator_with_space}+ cond:where_conditions} {blank})|(blank:/[\s\S]*/))
    ;

#include :: "linear_algebra/la_grammar/keywords.ebnf"
#include :: "linear_algebra/la_grammar/base.ebnf"
#include :: "linear_algebra/la_grammar/shared.ebnf"



identifier_alone::IdentifierAlone
    = !KEYWORDS(  value:/[A-Za-z][[A-Za-z0-9]*/ | value:/[A-Za-z\p{Ll}|\p{Lu}|\p{Lo}]/ | '`' id:/[^`]*/ '`')
    # !KEYWORDS value:/[^`;\n\r\f_\d]/ | '`' id:/[^`]*/ '`'
    #= !KEYWORDS value:/[A-Za-z]/ | '`' id:/[\p{L}\p{M}A-Za-z0-9\s\u2190-\u21FF\u1000-\uFFFFF]*/ '`'
    ;


KEYWORDS
    = BUILTIN_KEYWORDS
    ;

